version: '3.8'

services:
  php:
    container_name: store-php
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - COMPOSER_INSTALL_ARGS="--prefer-dist --optimize-autoloader"
        - PHP_ENV=dev
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: store-nginx
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:433"
    links:
      - php:php
    depends_on:
      - php

  db:
    image: postgres:latest
    container_name: store-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: 'store'
      POSTGRES_DB: 'book-store'
      POSTGRES_PASSWORD: 'strong_password'

volumes:
  db-data: